apiVersion: apps/v1
kind: Deployment
metadata:
  name: person
spec:
  selector:
    matchLabels:
      app: person
  replicas: 1
  template:
    metadata:
      labels:
        app: person
    spec:
      containers:
        - name: person
          image: person:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
