apiVersion: v1
kind: Namespace
metadata:
  name: invoice
  labels:
    client: att.com
    env: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: makcalif-cluster-admins
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "f78b303b-028a-4044-9e4f-bcddfcda4a3d"
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: makcalif-cluster-operators
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: operator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "f78b303b-028a-4044-9e4f-bcddfcda4a3d"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: makcalif-cluster-developers
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: developer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: "7b6b35d7-c40c-4ee9-a1af-5e06502def93"
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: invoice
  name: operator
rules:
- apiGroups: ["apps","extensions"]
  resources: ["deployments","configmaps","pods","secrets","ingresses"]
  verbs: ["create","get","delete","list","update","edit","watch","exec","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: invoice
  name: developer
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get","describe","list","watch","exec"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator
  namespace: invoice
roleRef:
  kind: Role
  name: operator
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: invoice
  name: operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer
  namespace: invoice
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: invoice
  name: developer

